# Generated by Django 2.0.7 on 2018-08-11 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('booking_color', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_tr', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_from', models.CharField(blank=True, default='', max_length=20)),
                ('return_tr', models.CharField(blank=True, default='', max_length=20)),
                ('return_to', models.CharField(blank=True, default='', max_length=20)),
                ('container_1', models.CharField(blank=True, default='', max_length=50)),
                ('container_2', models.CharField(blank=True, default='', max_length=50)),
                ('ref', models.CharField(blank=True, default='', max_length=50)),
                ('remark', models.CharField(blank=True, default='', max_length=200)),
                ('work_type', models.CharField(choices=[('empty', 'Empty'), ('full', 'Full')], default='empty', max_length=10)),
                ('work_id', models.CharField(blank=True, default='', max_length=50)),
                ('work_number', models.IntegerField(default=0)),
                ('pickup_date', models.DateField(blank=True, default='', null=True)),
                ('return_date', models.DateField(blank=True, default='', null=True)),
                ('address', models.CharField(choices=[('shipper', 'Shipper'), ('other', 'Other'), ('none', 'None')], default='shipper', max_length=10)),
                ('address_other', models.CharField(blank=True, default='', max_length=500)),
                ('cancel', models.CharField(choices=[('1', 'Cancel'), ('0', '-')], default=0, max_length=1)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper')),
            ],
        ),
    ]
