# Generated by Django 2.0.7 on 2018-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0002_auto_20180814_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='work_type',
            field=models.CharField(choices=[('ep', 'Empty'), ('fc', 'Full')], default='ep', max_length=10),
        ),
    ]
