# Generated by Django 2.1 on 2018-09-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0003_auto_20180814_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttransport',
            name='booking_color',
        ),
    ]
