# Generated by Django 2.1 on 2018-09-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0004_remove_agenttransport_booking_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransport',
            name='test',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
