# Generated by Django 2.1 on 2018-09-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0005_agenttransport_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttransport',
            name='test',
        ),
    ]
