# Generated by Django 2.1 on 2018-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_transport', '0006_remove_agenttransport_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttransport',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
