# Generated by Django 2.0.7 on 2018-07-23 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('booking_color', models.CharField(blank=True, default='', max_length=20)),
                ('fw_tr', models.CharField(blank=True, max_length=50)),
                ('fw_fm', models.CharField(blank=True, max_length=50)),
                ('container_no', models.CharField(blank=True, max_length=50)),
                ('seal_no', models.CharField(blank=True, max_length=50)),
                ('bw_tr', models.CharField(blank=True, max_length=50)),
                ('bw_to', models.CharField(blank=True, max_length=50)),
                ('vessel', models.CharField(blank=True, max_length=50)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('closing_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('closing_time', models.CharField(blank=True, default='', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('loading', models.CharField(blank=True, max_length=50)),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('pickup_date', models.DateField(blank=True)),
                ('factory_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
                ('pickup_in_time', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_out_time', models.CharField(blank=True, default='', max_length=20)),
                ('factory_in_time', models.CharField(blank=True, default='', max_length=20)),
                ('factory_load_start_time', models.CharField(blank=True, default='', max_length=20)),
                ('factory_load_finish_time', models.CharField(blank=True, default='', max_length=20)),
                ('factory_out_finish', models.CharField(blank=True, default='', max_length=20)),
                ('return_in_time', models.CharField(blank=True, default='', max_length=20)),
                ('return_out_time', models.CharField(blank=True, default='', max_length=20)),
                ('ref', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(choices=[('shipper', 'Shipper'), ('other', 'Other'), ('none', 'None')], default='shipper', max_length=10)),
                ('address_other', models.CharField(blank=True, default='', max_length=500)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Principal')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Shipper')),
            ],
        ),
    ]
