# Generated by Django 2.0.7 on 2018-07-23 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=20),
        ),
    ]
