# Generated by Django 2.0.7 on 2018-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180723_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='closing_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
