# Generated by Django 2.0.7 on 2018-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_work_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='work_number',
            field=models.IntegerField(default=0),
        ),
    ]
