# Generated by Django 2.0.7 on 2018-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20180724_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
