# Generated by Django 2.0.7 on 2018-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20180726_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closing_date',
            field=models.DateField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
