# Generated by Django 2.0.7 on 2018-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20180803_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.CharField(choices=[(1, 'Cancel'), (0, '-')], default=0, max_length=1),
        ),
    ]
