# Generated by Django 2.0.7 on 2018-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20180807_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='factory_out_finish',
            new_name='factory_out_time',
        ),
    ]
