# Generated by Django 2.1 on 2018-09-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20180901_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_color',
        ),
    ]
