# Generated by Django 2.1 on 2018-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_booking_booking_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cut',
            field=models.CharField(choices=[('1', 'Cut'), ('0', '-')], default=0, max_length=1),
        ),
    ]
