# Generated by Django 2.1 on 2018-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cut',
        ),
        migrations.AddField(
            model_name='booking',
            name='nextday',
            field=models.CharField(choices=[('1', 'Yes'), ('0', '-')], default=0, max_length=1),
        ),
    ]
