# Generated by Django 2.0.7 on 2018-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='work_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('agent-transport', 'Agent-Transport')], default='normal', max_length=20),
        ),
    ]
